os: linux
dist: xenial
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
- hugo version
- hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_711f30a834c1_key -iv $encrypted_711f30a834c1_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.71.1
  - secure: f4+EmgCvRVCJp4lQBiJnAJBOJGdKHg1/+1qbs9UM59D531M5S6y6uS1NCc8W6GowePV0R0UqWC1hV/xMYepQ+MN1uZEcDLAqyveniz7Odwf4pXAm8ilSzbgfa+q7JLvu/1SjC5LhFtdFDVTMHxCJ+Q4CJj4t1Uf8gHfDbIBIFBuX4aQ3Ko8YOVtUUofNwQHEVd+5k+Qe3aaCxBV6wE+h5Slzv8uXydYMo06PKJZV0UeT3iXj/NUgLnMtmB6D6daUy1KIBTHn9xo5ObteHgxaIRVf+nZqHePK6CoC5uGBzsX+Ji+dP/CYB3J/RZzL3rjObTE3jBg+aPbm5NAgTSd529M2JZMVJV8R3Pmp39Opfr044tJBG5P9ZXhs5aAABI3aRXAXt4eKaySMqct6laBeE9FV2yAAtrowm10dXrMeddsAhqUK898HlNC71XHoySh0jQQ0H6OPOzuwKKcSrQ88p9adYqIlsBXZBgEe6Qa5z8X28uTeZn5SryXuuMN9d71AeO1mW0vMhPtbZ3m4YEZLeQv8UGNQ6p4IBoVbA46FrGov8H28k2f7RhYtAdBoVxFe24NAjMPOr98mhGQhfDxNrjZj8HqwTmoCvJxqy95kLsRYtKlI2bfLuF9diZs76qAvQ0mc6p6mb1uH83NgVb6oyuqwOZXLYIF6YNuJI7ADyfA=
  - secure: TJ5fwdXnhyQ2bgri3t8W0EcfefpQZuDFvPVXiu3TyirQAR6f7TnlXAczYzw79YbXjPllOgZuL2j+Jtqax9m6msDY+b87VCJ2x2iBcLOythE7Pr2L7bvmCEMver70nizPtLf8oZA6+3uj+uKhWeScYHEsEkOQe4dd/ZLd93En52N6D6ug/XCpSHBCa5vnX7dLZW40nfpfvmFysAcHhUAwnmiCIAF3lk6biKk3xYpwp531h7dYogVXhILFCqquzUhWvtpVXs7tzV9RVdnxj1mPC/Kt1Oj2PVPobOEO/pgv2mQWudJd13+XeR5g7GPp2CkqvE206ufAc/3cIv09udqqMnjTmTggbPs4IYZR8jpxJLZQMU49LTdeLmComZARaC74dhD80IRljRvnLV9wgj/tbVpvtdL9eqmvPRWy/kbozok8mWS2XyKlZunjJk6WJPzr5TDlo+26CbcY/Pd7ibO4AeZ6cWVlwo4GGTvr7gGerkm5d9sM3ybERozYDoGtfUrLxwcCq/Vugxn+Mv/GSNwUdSr9Hwi+lweEeypghbFRz/3ffMgQBZ+CdS37yahFgBID0jlWWAk3PGRt3v9IUZvdxUBTn+MVNqk2SJrbT7QAtLlF0oAdjboZousg5RZzey1SSnbildXQ3EGd2RfRDZqUJo2dXQFMd0UUna6NWlNqQpo=
  - secure: dVySI0GL8tdJgaladbW05+dqq5PUgfC5pIXIHkq13kj11fiZSOQzzhFAXrLLgQJCgpDgcq9cM1IcZf87WYK0iWTmvmrXJ56bvwW5zWddg1MuEloOHwq4hHM3q/NXmAo1/U0chhRpvbpL/1lzuldBBCkyJSs4xADH7RNmT+UgklrXRbS84Wpa/cEyhbzEHUbzf6vTtmKZd0Lm9hWvM66LxyI0TCF9gFqK3ISiJK6Exert/dHWV5/U0s+INyA/9RW91W992i9CdOeyY6DZ3RRBvvagMiXOiCoVYDm47BxJSekIXIKQ2IWls9QNoRjgdlz3OsY5Z/wyWs9AgMJdnqlu+q03VgsXw8tjG59Ho2kwP5O1a8yg3g8xNWsU5J3bBgPA5vAC7Xcfo5lBtiXneedo80yBSM3kbxEoaS07XPRhDtyQb1G8Ga3YLAp00Ug3eplQA8BvW1ly2TZHdm/L5ZGc4LxrnnclSq8tadW4nWfQPxymMFCCb60kl+li2gqCv+KWG4R1He34VxHiE/fXTV+TjDT4NqJN8pNRRsKfhRxsKbB8wonwwbdvYleiDhwdsSIzlTZKpedXPGRnB3A6Y15q5eaSujS/ta2xKp6Qvqd3yNp41RBLr0LJIFXgdQHCJVpZVDZ32PGgYgDXgaaNvddAbCtkOSmQC3VW/wyzBXxN/eY=
