baseURL = "https://csullender.com/"
title = "Colin Sullender"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = false
enableGitInfo = true

pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "solarized-dark"

disqusShortname = "csullender"
googleAnalytics = "UA-26412009-1"
enableRobotsTXT = true

[taxonomies]
    tag = "tags"


# Theme Parameters
[params]
    author = "Colin Sullender"
    info = "Postdoctoral Researcher and Biomedical Engineer"
    description = "Welcome to the personal website of Colin Sullender, a postdoctoral researcher at the University of Texas at Austin specializing in optical imaging system design and digital image processing for biomedical applications."
    keywords = "personal,blog,biomedical,engineer,optics,researcher"

    avatarurl = "images/avatar.jpg"
    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    colorscheme = "light"
    hidecredits = false
    hidecopyright = false
    rtl = false
    math = false

    commit = "https://github.com/shiruken/csullender.com-hugo/tree/"


# Menu Links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts"
[[menu.main]]
    name = "Research"
    weight = 3
    url  = "/research"
[[menu.main]]
    name = "Coding"
    weight = 4
    url  = "/coding"
[[menu.main]]
    name = "Websites"
    weight = 5
    url  = "/websites"
[[menu.main]]
    name = "Science GIFs"
    weight = 6
    url  = "https://sciencegifs.csullender.com/"


# Social Links
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/csullender/"
    target = "_blank"
[[params.social]]
    name = "ResearchGate"
    icon = "fab fa-researchgate"
    weight = 2
    url = "https://www.researchgate.net/profile/Colin_Sullender"
    target = "_blank"
[[params.social]]
    name = "ORCID"
    icon = "fab fa-orcid"
    weight = 3
    url = "https://orcid.org/0000-0003-4329-7708"
    target = "_blank"
[[params.social]]
    name = "GitHub"
    icon = "fab fa-github-square"
    weight = 4
    url = "https://github.com/shiruken/"
    target = "_blank"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter-square"
    weight = 5
    url = "https://twitter.com/shiruken/"
    target = "_blank"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 6
    url = "https://www.instagram.com/shiruken/"
    target = "_blank"
[[params.social]]
    name = "Reddit"
    icon = "fab fa-reddit-square"
    weight = 7
    url = "https://www.reddit.com/user/shiruken"
    target = "_blank"
[[params.social]]
    name = "LastFM"
    icon = "fab fa-lastfm-square"
    weight = 8
    url = "https://www.last.fm/user/shiruken"
    target = "_blank"
[[params.social]]
    name = "Goodreads"
    icon = "fab fa-goodreads"
    weight = 9
    url = "https://www.goodreads.com/user/show/6443902-colin"
    target = "_blank"
[[params.social]]
    name = "Pinterest"
    icon = "fab fa-pinterest-square"
    weight = 10
    url = "https://www.pinterest.com/shiruken/"
    target = "_blank"